CREATE TABLE "GCG_4053_NOTES"(
 "RMA_ID" CHAR(15),
 "RES_TEXT" CHAR(500),
 "QA_NOTES" CHAR(500),
 "CAR_PART_NOTES" CHAR(500),
 "NON_COMF_TXT" CHAR(500),
 "API_PART_FLAG" CHAR(1),
 "NCMR_FLAG" CHAR(1),
 "CAR_FLAG" CHAR(1),
 "FRNCR_FLAG" CHAR(1),
 "QA_COMPLETE" CHAR(1),
 "EMPL_LAST_CHANGE" CHAR(20),
 "DATE_LAST_CHANGE" DATE);